const swaggerAutogen = require("swagger-autogen")();

const options = {
    info: {
        version: "1.0.0",
        title: "DataLabs APIs Documentation",
        description: "This APIs Documentation automatically generated by the <b>swagger-autogen</b>.",
        contact: { name: "- Sanjay Sharma", email: "sanjay.sharma@zappian.com" }
    },
    host: 'localhost:5000',
    basePath: "",
    schemes: ["http", "https"],
    consumes: ["application/json"],
    produces: ["application/json"],
    tags: [
        // {
        //     "name": "User",
        //     "description": "Endpoints"
        // }
    ],
    // securityDefinitions: {
    //     apiKeyAuth: {
    //         type: "Api Key",
    //         in: "Header", // can be "header", "query" or "cookie"
    //         name: "Authorization", // name of the header, query parameter or cookie
    //         description: "<b>Please Enter Authorization Token</b>"
    //     }
    // }
};

const outputFile = '../swagger/definition-output.json';
const routes = ['../../routes/main/*.js'];

swaggerAutogen(outputFile, routes, options);